### ISSUE TITLE
update PBI for arable systems

### ISSUE THREAD

**Issue by gerardhros** [AgroCares/Open-Bodem-Index-Calculator#120]
in 2021 the soil analysis evaluation for phosphorus has been updated.
see handboekbodemenbemesting.nl
documentation is available with Romke / Wim.

**Comment by yuki-nmi** [comment]
While analyzing P scores for whole NL, a question arose if the calculated P scores for grassland are too strict.

The old formula for PBI grassland is as follows:
` dt[crop_phosphate == "gras", value := 2 + 2.5 * log(A_P_PAE) + 0.036 * A_P_PAL / A_P_PAE]`
The new formula for PBI grassland is as follows:
`  dt[crop_phosphate == "gras", value := log(A_P_CC) * (-0.0114 * A_P_AL + 2.5) + 0.0251 * A_P_CC + 2]`

The PBI values of grassland are ca. 1 lower when calculated with the new formula. The figure below shows the PBI values calculated with old (x-axis) and new (y-axis) formula for all grassland parcels of the whole NL (N=516731). The input values are Bodemschat prediction of BRP2019. With the new formula of PBI, 16% of grassland parcels have a low PBI value (PBI < 2.5) , whereas with the old formula only 0.5% have a low PBI value.

![PBI_grassland_old_vs_new](https://user-images.githubusercontent.com/54851556/129576164-c92ca7e3-9ca5-4768-9c07-d1c2145a801b.jpg)

Low PBI values are usually associated with low A_P_CC value.

![PAL_PAE_grassland](https://user-images.githubusercontent.com/54851556/129577321-13609a6a-9b02-4835-b654-d14480ad6eca.jpg)

A question is if this relatively many parcels with low PBI reflect the reality. Is the new formula too strict? Or, is the input values of A_P_CC not accurate??

**Comment by yuki-nmi** [comment]
Discussed with Debby. Low availability in peat soil (and peaty clay soil) is rather common, so the relatively high % of parcels with low I_C_P values are plausible.
