### ISSUE TITLE
indicators occuring in weights.obic but not in column_description_obic

### ISSUE THREAD

**Issue by BrentWHR** [AgroCares/Open-Bodem-Index-Calculator#124]
I_P_MS, I_P_BC, I_B_SB occur in weights.obic but do not occur in column column_description_obic.
Probably I_P_MS is outdated and replaced by other water indicators
I_P_BC (bearing capacity?) does not exist (yet?)
I_B_SB?

**Comment by BrentWHR** [comment]
#123 includes a check to ppr_weights.R to make it easy to discover such superfluous indicators in weight.obic

**Comment by gerardhros** [comment]
thanks. weights.obic is updated.
I_P_MS has been replace by two other functions, see adaptations in ppr_weights.R
I_B_SB has been deleted, and I_P_BC is added.
