### ISSUE TITLE
obic_field_dt not handeling ID correctly

### ISSUE THREAD

**Issue by BrentWHR** [AgroCares/Open-Bodem-Index-Calculator#130]
When obic_field_dt calls obic_field it does so with the default ID for obic_field ` ID = 1,output = output)`.
This is fine if just running obic_field but not if one has multipile fields.
Down the road, having all fields with the same ID will give issues such as in calc_grass_age.

Perhaps obic_field_dt should require an ID column that can be used when calling obic_field.

**Comment by gerardhros** [comment]
obic_field is designed for a single field (as the function help explains).
same for obic_field_dt().

running obic_field for multiple fields, might need either a separate function, or an update of the obic_field by using functions by group in this wrapper function.

**Comment by BrentWHR** [comment]
A function or option to handle multipile fields at once might be nice.

I do think obic_field_dt should't call obic_field with ID = 1. Because this makes passing an ID to obic_field_dt useless. I think "ID=1" can be removed from the function call in obic_field_dt, its already the default in obic_field, let obic_field set ID to 1 if no ID is given to obic_field_dt

**Comment by yuki-nmi** [comment]
obic.R and obic_recommendations.R were modified, so that the wrapper function obic_field_dt can handle multiple sites simultaneously. 
See pull request #141.

**Comment by gerardhros** [comment]
has been merged into development 7-9-21
