### ISSUE TITLE
non ASCI characters in column_description and crop.obic

### ISSUE THREAD

**Issue by BrentWHR** [AgroCares/Open-Bodem-Index-Calculator#137]
column_descriptionn.obic has non-ASCI character:
 column       type           description_nl                        description_en unit method
 D_CP_MAIS derivative Fractie maÃ¯s in rotatie The fraction of mais in crop rotation    -   <NA>

crops.obic has non-ASCI character:
 crop_code                                     crop_name
 2951 aardappelen, consumptie op klei/l?î“??ssgrond

Not sure when these were introduced. These seem to occur both in development and master

**Comment by BrentWHR** [comment]
solved by 70ebdeacb55c9a6f2054a613b0086a1f9d42f016

**Comment by gerardhros** [comment]
is included in development branch.
