### ISSUE TITLE
Root depth for maize

### ISSUE THREAD

**Issue by yuki-nmi** [AgroCares/Open-Bodem-Index-Calculator#143]
Root depth is 10cm for mais and grassland, 30cm for arable land and nature ('root_depth.R'). The root depth influences the conversion of SOM (%) to D_OC (kgC/ha), and D_OC is the input parameter for D_NLV. Due to the difference in root depth, NLV is much higher for arable land than maize when the SOM level is the same.
Consequently, the indicator for N (I_C_N) is often very low for maize (median 0.52 for whole NL) compared to arable land (median 0.9). Furthermore, indicator for N retention (I_E_NSW and I_E_NGW) are often high for maize (median 0.98 and 0.96) irrespective of their high leaching fraction. This sounds like an artefact.

Action needed: Re-consideration of root depth for mais in 'root_depth.R'.  It should be deeper, e.g. 25 cm (measurement depth for maize field)??

**Comment by gerardhros** [comment]
the NLV calculation for grass is an empirical function calibrated on long-term experiments. Its different from the function for arable land, that is based on a model estimation or C decomposition. So, SOM should only have impact on non-grassland soils. 
Indeed, depth for maize should be 25 cm, comparable to all arable crops.
