### ISSUE TITLE
crop_eos is for 13 crops too high

### ISSUE THREAD

**Issue by SvenVw** [AgroCares/Open-Bodem-Index-Calculator#162]
For several crops the `crop_eos`  in `crops.obic` is extremely high and probably not correct. This will result in inaccurate organic matter balances

![image](https://user-images.githubusercontent.com/37927107/153364123-67143447-13cc-451b-bd9e-62275e3f369c.png)

**Comment by gerardhros** [comment]
i asked brent to check and update. @BrentWHR , can you make a branch to fix this?

**Comment by BrentWHR** [comment]
I'm pretty sure this has to do with perspotjes somehow. I found an older list with EOS values for this crops with and without perspotjes. The values with perspotjes are not integer Andijvie with perspotje for example: 2882.304 (barring the decimal seperator the same number as in the current list)
All other values without perspotjes are integer. I suspect the decimal seperator got lost somewhere either in conversions to and from csv, mixing up decimal seperators, or forcing integers somewhere.

I'm not sure to which brp crop the perspotjes belong and where we can best restore this.
