### ISSUE TITLE
`sVI` for B_GWL_CLASS gives assertion error

### ISSUE THREAD

**Issue by SvenVw** [AgroCares/Open-Bodem-Index-Calculator#173]
The value `sVI` for `B_GWL_CLASS` gives an assertion error. This is a valid groundwater class so this value should be accepted

**Comment by BrentWHR** [comment]
This issue was solved somewhere between versions 1.0.3 and 2.0.1.
The formatting function `format_gwt()` was added so 'sVI' is formatted as 'GtVI` which is expected by the checkmates
