### ISSUE TITLE
Not all GWT are supported for B_GT

### ISSUE THREAD

**Issue by SvenVw** [AgroCares/Open-Bodem-Index-Calculator#64]
The function `calc_waterstressindex` does not support `B_GT` with a suffix (e.g. `b`) or if no gwt is present (e.g. `-`).

**Comment by BrentWHR** [comment]
nleach_table does include Gt suffixes, so suffixes cannot be stripped. If there is no difference for calculating waterstress between "GtII" and "GtIIb" we can add rows for suffixes to waterstress.obic.
This will not solve gwt not present.

**Comment by gerardhros** [comment]
this is solved in testing_v1.2.0, commit ff0dfa. merged into release/v1.2.0
