### ISSUE TITLE
missing crop codes in crop table

### ISSUE THREAD

**Issue by yuki-nmi** [AgroCares/Open-Bodem-Index-Calculator#72]
Crop code 657 (Drachtplanten) and 1932 (Uien poot en plant eerstejaars), which appear in BRP2019 parcel shape file, are not included in the crops.obic table.
These crop codes 657 is equivalent to 428, and the crop code 1932 is equivalent to 1931.

**Comment by gerardhros** [comment]
making crops.obic is now part of package, in dev.
missing crop names 2020 are added
new column names have been added in br_improve_cropsobic and merged into v1.0.0
crops.obic description are given in br_obi_nematodes, and when finished will be merged into v1.1.0
