### ISSUE TITLE
Need re-consider weighing factors of I_P_x variables for S_P_A calculation

### ISSUE THREAD

**Issue by yuki-nmi** [AgroCares/Open-Bodem-Index-Calculator#75]
The weighing factors of I_P_MS (waterstress) and I_P_WRI (water retention) to calculate S_P_A is set to be 0. These indicators, however, take important roles and therefore they may need to be included in the calculation of S_P_A.

**Comment by gerardhros** [comment]
weighing procudure is updated in upOBIframework. Is merged into release/v1.2.0.
