### ISSUE TITLE
Set minimum for weighing factor for S_C_A

### ISSUE THREAD

**Issue by yuki-nmi** [AgroCares/Open-Bodem-Index-Calculator#82]
The chemical score S_C_A is originally calculated as follows:
`  dt.ind[, S_C_A := ((w$W_C_N + 1/I_C_N) * I_C_N + (w$W_C_P + 1/I_C_P) * I_C_P + w$W_C_K * I_C_K + 
					w$W_C_MG * I_C_MG + w$W_C_S * I_C_S +(w$W_C_PH + 1/I_C_PH) * I_C_PH + 
					w$W_C_CEC * I_C_CEC + (w$W_C_CU + w$W_C_ZN) * (I_C_CU + I_C_ZN)) / 
					  (1 + 1/I_C_N + 1/I_C_P + 1/I_C_PH)]`
When one of the three important indicators (N, P, pH) scores low, they are heavily weighed by multiplying with their inverse (e.g. 1/I_C_PH).
This results in too strong weight when the indicator value is very low, let's say <0.1.

To avoid that, I proposed to set a maximum value for the weighing factor (1/0,1 = 10), as follows:

`  dt.ind[, S_C_A := ((w$W_C_N + 1/max(0.1,I_C_N)) * I_C_N + (w$W_C_P + 1/max(0.1,I_C_P)) * I_C_P + w$W_C_K * I_C_K + 
					w$W_C_MG * I_C_MG + w$W_C_S * I_C_S +(w$W_C_PH + 1/max(0.1,I_C_PH)) * I_C_PH + 
					w$W_C_CEC * I_C_CEC + (w$W_C_CU + w$W_C_ZN) * (I_C_CU + I_C_ZN)) / 
					  (1 + 1/max(0.1,I_C_N) + 1/max(0.1,I_C_P) + 1/max(0.1,I_C_PH))]`

Pull request was made here: #83

**Comment by yuki-nmi** [comment]
I made another change on S_C_A.
S_C_A sometimes gets larger than 1, because sum of all weighing factor is larger than 1 (as w$W_C_CU and w$W_C_ZN are summed up).
I split the terms of Cu and Zn, so that S_C_A never becomes larger than 1.

**Comment by gerardhros** [comment]
this has been solved in branch set_min_lscore and has been merged into release/v1.0.0
