### ISSUE TITLE
Very low Mg indicator values for grassland on clay and peat

### ISSUE THREAD

**Issue by yuki-nmi** [AgroCares/Open-Bodem-Index-Calculator#84]
In Rijnland dataset, ca. 18% of parcels get a very low score for Mg (I_C_MG < 0.1). It's rather strange, because the A_MG_CC values of these parcels are moderate.

The low scores of I_C_MG comes from very low Mg-getal ('D_MG') of grassland on clay and peat. D_MG were computed based on regression model built on empirical dataset. It can be that the original dataset misses certain types of soils, and therefore the estimated D_MG for those soils are not realistic. 

YF consulted WB about the issue. The reaction of WB on 6-1-2021: 
_Ik heb nog niet direct een oplossing voor Mg veen en klei. Erg lage Mg-gehalten in gras kunnen voorkomen op deze gronden, althans in het verleden. De vraag is of dat nu ook nog regelmatig voorkomt. Daarvoor zouden we wat recentere data van gras moeten hebben. Wordt vervolgd_

Thus, a follow-up is needed to check if the evaluation of Mg for grassland on clay and peat is realistic.

The behavior of the regression model against input variables are illustrated below (horizontal facet is OS, vertical facet is pH). Under certain combination of input variables (e.g. low pH and/or high clay content in peat soil), D_MG values gets very low irrespective of high A_MG_CC value.

[Grassland on clay]
![image](https://user-images.githubusercontent.com/54851556/104710790-c88a2a00-5720-11eb-8b08-350c1aa67163.png)

[Grassland on peat]
![image](https://user-images.githubusercontent.com/54851556/104710847-d9d33680-5720-11eb-9062-0d0c046bb9aa.png)

**Comment by gerardhros** [comment]
this is solved in yf_modify_Mg2 isnt @yuki-nmi ?
If yes, then this issue can be closed.

**Comment by yuki-nmi** [comment]
The empirical function to estimate Mg for grassland on clay and peat is updated (#110). Now few parcels receive low I_C_MG score.
