### ISSUE TITLE
crops.obic description is incomplete

### ISSUE THREAD

**Issue by BrentWHR** [AgroCares/Open-Bodem-Index-Calculator#87]
Is described as: A data.frame with 405 rows and 12 columns
with descriptions for columns: crop_name, crop_code, crop_crumbleability, crop_phosphate, crop_sealing, crop_n
but is:
A data.table with 404 rows and 19 columns
 "crop_code", "crop_name", "crop_waterstress", "crop_intensity", "crop_eos", "crop_eos_residue", "crop_category", "crop_rotation"       "crop_crumbleability", "crop_phosphate", "crop_sealing", "crop_n", "crop_k", "crop_measure", "nf_clay", "nf_sand.other"       "nf_sand.south", "nf_loess", "nf_peat"

**Comment by SvenVw** [comment]
Do you mind to solve this issue in a PR together with #72?

**Comment by BrentWHR** [comment]
I'll see what I can do.

**Comment by BrentWHR** [comment]
To tackle #72 I need to modify the helpers repo where crops.obic is created. Can you give me permission to push to OBIC-helpers?

**Comment by gerardhros** [comment]
is solved, and merged into v1.0.0.
final update is in br_obi_nematode and after merge in v1.1.0 available for next versions.
