### ISSUE TITLE
Values in bodemschat outside range accepted by obic

### ISSUE THREAD

**Issue by BrentWHR** [AgroCares/Open-Bodem-Index-Calculator#88]
examples:
A_CA_CEC value of 579 > 400 (ID = 1570933f2417f62d73a8a289deb8e9a7703c68a07e34d4729142f562ccedb674)
A_MG_CECvalue of 65  > 50 (ID = 1f8ee9715495c5f27539ae0dac8885ff6959197466b61e2865ee5e52e19bce01)

**Comment by SvenVw** [comment]
We have to check if those values from BodemSchat are realistic. Otherwise replace them with the maximum of OBIC

**Comment by BrentWHR** [comment]
@gerardhros said in person that the ranges in OBIC are estimates. Either a check on BodemSchat or reassesment of the ranges in OBIC is required.
For now, manually replacing values with the maximum of OBIC works.

**Comment by gerardhros** [comment]
likely solved in gr_testing_release_1.2.0
