### ISSUE TITLE
wind_erodibility

### ISSUE THREAD

**Issue by gerardhros** [AgroCares/Open-Bodem-Index-Calculator#89]
in calc_wind_erodibility dt is merged with crops.obic, but not sorted on id.
this might results in wrong D_P_DU when sending output of calc back to indicator to dt.ppr.

**Comment by BrentWHR** [comment]
This has already been tackled in #85

**Comment by gerardhros** [comment]
this is solved in yf_fix_D_P_DU and merged into release/v1.0.0
