### ISSUE TITLE
waterstress of Spelt is 'overig', 'cereal' seems more appropriate

### ISSUE THREAD

**Issue by BrentWHR** [AgroCares/Open-Bodem-Index-Calculator#93]
In crops.obic crop_waterstress of Spelt is 'overig'. Probably 'cereal' would better reflect the waterstress of this crop.
Spelt is one of the crops used in the testthat test. So the test also needs to be changed if Spelt's waterstress is corrected.

**Comment by gerardhros** [comment]
seems to be solved by Brent in br_improve_crops.obic? @BrentWHR?

**Comment by BrentWHR** [comment]
> seems to be solved by Brent in br_improve_crops.obic? @BrentWHR?

Was solved but this invalidated the test-that test for calc_waterstressindex as 'spelt' is one of the crops in the test (crop_code == 382). I reverted the changes in a later commit as I wasn't sure how to change the test. 
Might be as simple as changing the crop code in the test to that of another crop with crop_waterstress == 'overig'. For example: 664, raapzaad.

**Comment by gerardhros** [comment]
solved in branch br_crops.obic and merged into release/v1.1.0
